### ISSUE TITLE
Problems with node.js?

### ISSUE THREAD

**Issue by maresb** [conda-forge/code-server-feedstock#17]
Sorry for the terse bug report. I don't have time to properly diagnose things right now, but I wanted to make a note.

For context, due to undesired downgrading, I recently unpinned nodejs=12.* in #16. However, the latest version seems broken for me. I just realized that the releases of code-server bundle their own Node.js. In contrast, this feedstock uses conda's Node.js. (Checking Help → About in my native VS Code it reports that it uses Node.js 12.8.1, while Conda's preferred 12.* version for my environment is 12.16.1. 

This situation seems problematic to me since I imagine that the code-server devs will probably only ever test with their bundled version. 

Things seem to work using the bundled version upon replacing `node` with `${CONDA_PREFIX}/share/code-server/lib/node` in the `code-server` script.

Would it make sense to go this route of using the bundled `node` and remove the `nodejs` dependency entirely? If you agree, I could submit a PR later in case you don't get to it first.

**Comment by xhochy** [comment]
The whole sense of this package is to use conda-forge packages where possible and thus also the `nodejs` (and `openssl`, ...) from conda-forge. We sadly switched to repackaging the code-server binary in the last release because the build-from-source did fail but should actually strive to the get build-from-source back in again.

If you want to use the bundled version of node in code-server, you should simply download their tarballs.

**Comment by maresb** [comment]
Ok, thanks for the clarification. I will close this issue and PR.
